version: '3'
services:

  app-two:
    image: docker-app-with-db-controller
    container_name: docker-app-with-db-controller
    ports:
      - 5051:4040
    depends_on:
      - db
  db:
    image: mysql
    container_name: docker-app-db
    restart: always
    environment:
      MYSQL_DATABASE: 'example'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    ports:
      - 4444:3306
    volumes:
      - example:/var/lib/mysql
  app:
    image: docker-app-with-link
    container_name: docker-app-with-link
    ports:
      - 5050:4040
volumes:
  example:

